### ISSUE TITLE
Redirect from payment provider results in a blank page 

### ISSUE THREAD

**Issue by CptCompiler** [heidelpay/woocommerce-heidelpay#13]
After payment is done I am getting redirected to my website with a blank page. The called URL is localhost/wc-api/wc_gateway_hp_va.
I think that the problem is that there are no $_POST parameters which should be handled in the callback_handler function in /woocommerce-heidelpay/includes/abstracts/abstract-wc-heidelpay-payment-gateway.php.
I am using the Heidelpay test accounts. Am I doing something wrong?

I would appreciate some help.
Thanks

**Comment by Ryouzanpaku** [comment]
Hello @CptCompiler,
you are testing from a local System. Your response-URL has to be accessible from outside because our payment system tries to send the post data to "localhost/wc-api/wc_gateway_hp_va". But localhost can not be reached from outside. As a result the payment server can't get the redirect-URL. In that case the user is redirectet to the given response-URL directly.

**Comment by CptCompiler** [comment]
Ahhh, I understand.
I will try it on our live server.
Thank you very much!
